INSERT INTO trails (id, name, location, type, biome, difficulty, length, image)
VALUES (1, 'Aklā purva taka', 'Daudzeses pagasts, Aizkraukles novads, LV-5111', 'Gājēju taka', 'Purvs', 'Viegli', 1.9,
        'trails/1.jpg'),
       (2, 'Akmeņu taka', 'Jaunstašuļi, Mākoņkalna pagasts, Rēzeknes novads, LV-4626', 'Gājēju taka', 'Mežs', 'Normāli',
        2.3, 'trails/2.jpg'),
       (3, 'Amatas ģeotaka. Melturi - Kārļu zivjaudzētava',
        'Drabešu pagasts, Cēsu novads. Melturi: 57.2218595, 25.2359774. Kārļu zivjaudzētava: 57.2374353, 25.2011978',
        'Gājēju taka', 'Mežs, upe', 'Grūti', 3.6, 'trails/3.jpg'),
       (4, 'Amatas ģeotaka. Kārļu zivjaudzētava - Zvārtes iezis',
        'Drabešu pagasts, Cēsu novads. Kārļu zivjaudzētava: 57.2374353, 25.2011978 Zvārtes iezis: 57.2459047, 25.1432441',
        'Gājēju taka', 'Mežs, upe', 'Normāli', 9.2, 'trails/4.jpg'),
       (5, 'Amatas ģeotaka. Zvārtes iezis - Veclauču tilts',
        'Drabešu pagasts, Cēsu novads. Zvārtes iezis: 57.2459047, 25.1432441; Veclauču tilts: 57.2617720, 25.1379117',
        'Gājēju taka', 'Upe', 'Viegli', 2.4, 'trails/5.jpg'),
       (6, 'Andrupenes purva taka', 'Skolas iela 5, Andrupene, Andrupenes pagasts, Krāslavas novads', 'Gājēju taka',
        'Purvs', 'Viegli', 0.8, 'trails/6.jpg'),
       (7, 'Augstrozes pilskalna taka', 'Umurgas pagasts, Limbažu novads, LV-4004', 'Gājēju taka', 'Tīrums', 'Grūti',
        0.5, 'trails/7.jpg'),
       (8, 'Barona taka', 'Vilces pagasts, Jelgavas novads. 56.42091763152077, 23.54215030025643', 'Gājēju taka',
        'Mežs', 'Viegli', 2.5, 'trails/8.jpg'),
       (9, 'Bernātu dabas parka taka', 'Bernāti, Nīcas pagasts, Dienvidkurzemes novads, LV-3473', 'Gājēju taka', 'Mežs',
        'Grūti', 1.5, 'trails/9.jpg'),
       (10, 'Cenas tīreļa laipu taka', 'Babītes pagasts, Mārupes novads, LV-2107', 'Gājēju taka', 'Purvs', 'Viegli', 6,
        'trails/10.jpg'),
       (11, 'Cecīļu dabas taka', 'Cecīļu iela 12, Ieriķi, Drabešu pagasts, Cēsu novads, LV-4139', 'Gājēju taka', 'Mežs',
        'Grūti', 1.5, 'trails/11.jpg'),
       (12, 'Cīrulīšu takas Nr. 1', 'Apšukalna iela 5, Cēsis, Cēsu pilsēta, Cēsu novads, LV-4101', 'Gājēju taka',
        'Mežs', 'Normāli', 2.5, 'trails/12.jpg'),
       (13, 'Cīrulīšu takas Nr. 2', 'Apšukalna iela 5, Cēsis, Cēsu pilsēta, Cēsu novads, LV-4102', 'Gājēju taka',
        'Mežs', 'Normāli', 3.5, 'trails/13.jpg'),
       (14, 'Cīrulīšu takas Nr. 3', 'Apšukalna iela 5, Cēsis, Cēsu pilsēta, Cēsu novads, LV-4103', 'Gājēju taka',
        'Mežs', 'Normāli', 5.7, 'trails/14.jpg'),
       (15, 'Čužu purva taka', 'Kandava, Kandava pilsēta, Tukuma novads, LV-3120', 'Gājēju taka', 'Purvs', 'Viegli', 4,
        'trails/15.jpg'),
       (16, 'Daugavgrīvas dabas taka', 'Dabas parks Piejūra, Rīga. 57.03688, 24.01852', 'Gājēju taka, velotaka',
        'Purvs, tīrums', 'Viegli', 1, 'trails/16.jpg'),
       (17, 'Dabas procesu taka', 'Pape, Rucavas pagasts, Dienvidkurzemes novads, LV-3477', 'Gājēju taka',
        'Pļava, mežs, purvs', 'Normāli', 9.1, 'trails/17.jpg'),
       (18, 'Dauģēnu taka', '57.87415, 24.99788', 'Gājēju taka, velotaka', 'Mežs', 'Grūti', 9.1, 'trails/18.jpg'),
       (19, 'Dinaburgas taka', 'Naujenes pagasts, Augšdaugavas novads. 55.911272 , 26.726717000000008', 'Gājēju taka',
        'Tīrums', 'Normāli', 0.6, 'trails/19.jpg'),
       (20, 'Drusku pilskalna taka', '57.59448, 26.93333', 'Gājēju taka', 'Mežs', 'Grūti', 3.5, 'trails/20.jpg'),
       (21, 'Dunikas purva taka', 'Dunikas pagasts, Dienvidkurzemes novads', 'Gājēju taka', 'Purvs', 'Viegli', 5,
        'trails/21.jpg'),
       (22, 'Dullā Daukas birzs', 'Meņģeles pag., Ogres nov. 56.839275511712025, 25.35594100668977', 'Gājēju taka',
        'Mežs', 'Viegli', 0.8, 'trails/22.jpg'),
       (23, 'Dziļezera-Riebezera taka', 'Jumpravmuiža, Limbažu pagasts, Limbažu novads, LV-4001', 'Gājēju taka',
        'Ezers', 'Grūti', 3.7, 'trails/23.jpg'),
       (24, 'Ellītes sēravota taka', 'Daudzeva, Daudzeses pagasts, Aizkraukles novads, LV-5111', 'Gājēju taka', 'Mežs',
        'Viegli', 0.3, 'trails/24.jpg'),
       (25, 'Embūtes taka Nr. 1', 'Embūtes pagasts, Dienvidkurzemes novads, LV-3436', 'Gājēju taka', 'Mežs', 'Grūti', 3,
        'trails/25.jpg'),
       (26, 'Embūtes taka Nr. 2', 'Embūtes pagasts, Dienvidkurzemes novads, LV-3437', 'Gājēju taka', 'Mežs', 'Grūti', 5,
        'trails/26.jpg'),
       (27, 'Ēvažu taka', 'Kurzeme, Ēvaži, Kolkas pagasts, Talsu novads', 'Gājēju taka', 'Piekraste', 'Normāli', 0.3,
        'trails/27.jpg'),
       (28, 'Gaujas taka Nr. 1', '57.623440, 25.690126', 'Gājēju taka', 'Upe', 'Normāli', 5, 'trails/28.jpg'),
       (29, 'Gaujas taka Nr. 2', '57.623440, 25.690127', 'Gājēju taka', 'Upe', 'Normāli', 7, 'trails/29.jpg'),
       (30, 'Gaujienas taka', '57.52202, 26.38903', 'Gājēju taka', 'Tīrums', 'Viegli', 6, 'trails/30.jpg'),
       (31, 'Imulas taka', 'Matkules pagasts, Tukuma novads, LV-3132', 'Gājēju taka', 'Mežs, upe', 'Normāli', 5,
        'trails/31.jpg'),
       (32, 'Jaundomes muižas taka',
        'Jaundomes muiža, Novomisļi, Ezernieku pagasts, Dagdas novads. 56.1480680999648, 27.61438996711629',
        'Gājēju taka', 'Mežs', 'Viegli', 2, 'trails/32.jpg'),
       (33, 'Bērza taka', 'Sarkaņkalns", Plikpūrmaļi, Vērēmu pagasts, Rēzeknes novads', 'Gājēju taka', 'Mežs',
        'Normāli', 2, 'trails/33.jpg'),
       (34, 'Baskāju taka', 'Kurzeme, Valgums, Atpūtas komplekss, Smārdes pagasts, Tukuma novads, LV-3129',
        'Gājēju taka', 'Tīrums', 'Viegli', 2.9, 'trails/34.jpg'),
       (35, 'Bišu taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Tīrums', 'Viegli', 0.2,
        'trails/35.jpg'),
       (36, 'Putnu taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Tīrums', 'Viegli', 0.2,
        'trails/36.jpg'),
       (37, 'Meža taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Mežs un upe', 'Normāli', 2.3,
        'trails/37.jpg'),
       (38, 'Augu taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Tīrums', 'Viegli', 0.7,
        'trails/38.jpg'),
       (39, 'Sporta taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Tīrums', 'Grūti', 0.5,
        'trails/39.jpg'),
       (40, 'Sietiņieža dabas taka', 'Sietiņiezis, Vaidavas pagasts, Valmieras novads, LV-4228', 'Gājēju taka', 'Mežs',
        'Viegli', 1.4, 'trails/40.jpg'),
       (41, 'Sedas purva kājnieku maršruts Jērcēnu aplis', 'Latvija, Vidzeme, Strenču novads, 57.7055987, 25.7001324',
        'Gājēju taka', 'Purvs', 'Normāli', 5.5, 'trails/41.jpg'),
       (42, 'Sedas purva kājnieku maršruts Sedas aplis', 'Latvija, Vidzeme, Strenču novads, 57.6699587, 25.7514815',
        'Gājēju taka', 'Purvs', 'Grūti', 7.5, 'trails/42.jpg'),
       (43, 'Melnalkšņu dumbrāju taka', 'Meža māja, Jūrmala, LV-2012', 'Gājēju taka', 'Mežs', 'Viegli', 0.6,
        'trails/43.jpg'),
       (44, 'Slokas ezera dabas taka', 'Dūņu ceļš, Jūrmala, LV-2012', 'Gājēju taka', 'Ezers', 'Viegli', 3.1,
        'trails/44.jpg'),
       (45, 'Vikmestes taka', 'Krimuldas pagasts, Siguldas novads, LV-2150', 'Gājēju taka', 'Mežs', 'Viegli', 3,
        'trails/45.jpg'),
       (46, 'Vizlas dabas taka', 'Vidaga, Virešu pagasts, Smiltenes novads, LV-4355, 57.43061, 26.34762', 'Gājēju taka',
        'Upe', 'Normāli', 1.2, 'trails/46.jpg'),
       (47, 'Raganu purva taka', 'Lapmežciema pagasts, Tukuma novads, LV-3118', 'Gājēju taka', 'Purvs', 'Viegli', 0.8,
        'trails/47.jpg'),
       (48, 'Kubeseles dabas un vēstures taka',
        'Krimuldas evaņģēliski luteriskā baznīca, Krimuldas pagasts, Siguldas novads', 'Gājēju taka', 'Mežs un upe',
        'Viegli', 3.9, 'trails/48.jpg'),
       (49, 'Brīvdabas taka gar Rojas upi mazais loks', 'Kāpu iela, Roja, Rojas pagasts, Talsu novads, LV-3264',
        'Gājēju taka, velotaka', 'Mežs un upe', 'Viegli', 2, 'trails/49.jpg'),
       (50, 'Brīvdabas taka gar Rojas upi vidējais loks', 'Kāpu iela, Roja, Rojas pagasts, Talsu novads, LV-3264',
        'Gājēju taka, velotaka', 'Mežs un upe', 'Normāli', 7, 'trails/50.jpg'),
       (51, 'Brīvdabas taka gar Rojas upi lielais loks', 'Kāpu iela, Roja, Rojas pagasts, Talsu novads, LV-3264',
        'Gājēju taka, velotaka', 'Mežs un upe', 'Grūti', 15, 'trails/51.jpg'),
       (52, 'Asares veselības taka', 'Aknīstes novads, Asares pagasts, Asare, Vecmuiža, LV-5210', 'Gājēju taka',
        'Tīrums', 'Viegli', 0.5, 'trails/52.jpg'),
       (53, 'Plieņciema laipu taka', 'Plieņciems, Engures pagasts, Tukuma novads, LV-3113', 'Gājēju taka',
        'Piejūras kāpa', 'Viegli', 3.5, 'trails/53.jpg'),
       (54, 'Gārsenes dabas takas', 'Gārsene, Gārsenes pagasts, Jēkabpils novads, LV-5218', 'Gājeju taka', 'Mežs',
        'Normāli', 7, 'trails/54.jpg'),
       (55, 'Ieriķu dzirnavu dabas taka', 'Ieriķi, Drabešu pagasts, Cēsu novads, LV-4139', 'Gājēju taka', 'Upe',
        'Normāli', 1, 'trails/55.jpg'),
       (56, 'Pokaiņu takas', 'Pokaiņi, "Senpokaiņi", Dobeles novads', 'Gājēju taka', 'Mežs', 'Normāli', 15,
        'trails/56.jpg'),
       (57, 'Ziemassvētku kauju piemiņas parka taka', '56.82956, 23.70139', 'Gājēju taka', 'Mežs', 'Grūti', 7.2,
        'trails/57.jpg'),
       (58, 'Latvijas vēstures taka Nītaurē', 'Nītaure, Nītaures pagasts, Cēsu novads, LV-4112', 'Gājēju taka', 'Mežs',
        'Viegli', 3, 'trails/58.jpg'),
       (59, 'Kalvu taka', 'Kaltene, Rojas pag., Talsu nov., 57.458110245127514,22.855964348726122', 'Gājēju taka',
        'Mežs', 'Grūti', 1.5, 'trails/59.jpg'),
       (60, 'Kartavkalna taka', '56.716568, 23.017921', 'Gājēju taka', 'Mežs', 'Viegli', 1.1, 'trails/60.jpg'),
       (61, 'Randātu dabas taka', 'Vireši, Virešu pagasts, Smiltenes novads, LV-4355', 'Gājēju taka', 'Klintis',
        'Normāli', 1.2, 'trails/61.jpg'),
       (62, 'Vīsraga dabas taka', '57.698035, 25.276864', 'Gājeju taka, velotaka', 'Pļava', 'Viegli', 2,
        'trails/62.jpg'),
       (63, 'Limbažu Lielezera taka', 'Lielezera iela 14, Limbaži', 'Gājeju taka', 'Ezers', 'Viegli', 2.3,
        'trails/63.jpg'),
       (64, 'Vekšu taka', 'Vekši, Valkas pag., LV-4701, 57.691150, 26.053069', 'Gājeju taka', 'Tīrums', 'Viegli', 0.5,
        'trails/64.jpg'),
       (65, 'Jāņkalnu folkloras taka', 'Jāņkalni", Lībagu pagasts, Talsu novads', 'Gājeju taka', 'Tīrums', 'Viegli',
        0.2, 'trails/65.jpg'),
       (66, 'Dabas taka "Rīvas loki', 'Jūrkalnes pagasts, Ventspils novads, LV-3626', 'Gājeju taka', 'Upe', 'Grūti', 8,
        'trails/66.jpg'),
       (67, 'Markovas izziņas taka un Markovas pilskalns', '55.916794 , 26.892548, Sprukti, Naujenes pagasts',
        'Gājeju taka', 'Mežs', 'Viegli', 1.6, 'trails/67.jpg'),
       (68, 'Kolkasraga priežu taka', 'Kolkas pagasts, Dundagas novads, 57.75690585102602, 22.591081627204712',
        'Gājeju taka', 'Mežs, tīrums', 'Viegli', 1.2, 'trails/68.jpg'),
       (69, 'Žibgravas veselības taka', '56.984217, 21.578783', 'Gājeju taka', 'Mežs', 'Normāli', 1.2, 'trails/69.jpg'),
       (70, 'Ukru gāršas takas', 'Bukaišu pagasts, Dobeles novads, LV-3714', 'Gājeju taka', 'Mežs', 'Normāli', 2,
        'trails/70.jpg'),
       (71, 'Viesatas upesloku taka', '56.81726, 22.94729', 'Gājeju taka', 'Mežs, upe', 'Normāli', 4, 'trails/71.jpg'),
       (72, 'Viesatas upesloku taka', '56.81726, 22.94730', 'Gājeju taka', 'Mežs, upe', 'Normāli', 6, 'trails/72.jpg'),
       (73, 'Akmeņupītes taka', 'Jaunstašuļi, Mākoņkalna pagasts, Rēzeknes novads', 'Gājeju taka', 'Mežs', 'Viegli',
        1.2, 'trails/73.jpg'),
       (74, 'Zaķumuižas dabas taka', 'Parka iela, Zaķumuiža, Ropažu pagasts, Ropažu novads, LV-2133', 'Gājeju taka',
        'Tīrums', 'Viegli', 1.8, 'trails/74.jpg'),
       (75, 'Sprīdīša taka', 'Pilskalne, Pilskalnes pagasts, Augšdaugavas novads', 'Gājeju taka', 'Tīrums', 'Viegli',
        1.6, 'trails/75.jpg'),
       (76, 'Dendroloģiskais un ģeogrāfiskais maršruts', 'Pilskalne, Pilskalnes pagasts, Augšdaugavas novads',
        'Gājeju taka', 'Mežs', 'Viegli', 3.8, 'trails/76.jpg'),
       (77, 'Taka “Vēstures liecinieki”', 'Pilskalne, Pilskalnes pagasts, Augšdaugavas novads', 'Gājeju taka', 'Mežs',
        'Viegli', 5, 'trails/77.jpg'),
       (78, 'Pilskalnes Siguldiņas purva taka', 'Pilskalne, Pilskalnes pagasts, Augšdaugavas novads', 'Gājeju taka',
        'Purvs', 'Normāli', 6, 'trails/78.jpg'),
       (79, 'Kaņiera niedrāja taka', 'Kaņiera ezera niedru taka, Lapmežciema pagasts, Tukuma novads', 'Gājeju taka',
        'Ezers', 'Grūti', 0.6, 'trails/79.jpg'),
       (80, 'Teirumnīku purva taka', 'Nagļu pagasts, Rēzeknes novads', 'Gājeju taka, velotaka', 'Ezers, purvs',
        'Viegli', 0.8, 'trails/80.jpg'),
       (81, 'Drubazu dabas taka', '57.030415, 22.59661', 'Gājeju taka', 'Pļava', 'Viegli', 1.2, 'trails/81.jpg'),
       (82, 'Drubazu dabas taka', '57.030415, 22.59662', 'Gājeju taka', 'Pļava', 'Normāli', 2, 'trails/82.jpg'),
       (83, 'Adamovas taka', 'Augusta iela 3A, Krāslava, Krāslavas pilsēta, Krāslavas novads, LV-5601', 'Gājeju taka',
        'Mežs, upe', 'Normāli', 1.8, 'trails/83.jpg'),
       (84, 'Niedrāju - Pilkas purva taka', 'Niedrāju–Pilkas purvs, Pāles pagasts, Limbažu novads', 'Gājeju taka',
        'Purvs', 'Viegli', 1, 'trails/84.jpg'),
       (85, 'Minhauzena taka', 'Duntes muiža, Liepupes pagasts', 'Gājeju taka', 'Mežs, Krasts', 'Viegli', 1.1,
        'trails/85.jpg'),
       (86, 'Minhauzena taka', 'Duntes muiža, Liepupes pagasts', 'Gājeju taka', 'Mežs, Krasts', 'Viegli', 3,
        'trails/86.jpg'),
       (87, 'Minhauzena taka', 'Duntes muiža, Liepupes pagasts', 'Gājeju taka', 'Mežs, Krasts', 'Viegli', 4.4,
        'trails/87.jpg'),
       (88, 'Ragakāpas dabas taka', 'Tīklu iela 1a, Buļļuciems,  56.9961349, 23.9155135', 'Gājeju taka', 'Mežs',
        'Normāli', 2, 'trails/88.jpg'),
       (89, 'Murjāņi - Sigulda taka', 'Puķu iela 4, Sigulda', 'Gājeju taka, velotaka', 'Mežs, upe, tīrums', 'Grūti',
        30.2, 'trails/89.jpg'),
       (90, 'Šlīteres dabas taka', 'Slīteres dabas taka, Dundagas pagasts, Talsu novads, LV-3270', 'Gājeju taka',
        'Mežs, purvs', 'Normāli', 1.2, 'trails/90.jpg'),
       (91, 'Saulrieta taka', 'Rīgas iela 11A, Saulkrasti, Saulkrastu pilsēta, Saulkrastu novads, LV-2160',
        'Gājeju taka', 'Mežs, piekraste', 'Viegli', 3.6, 'trails/91.jpg'),
       (92, 'Jēču dabas taka', 'Jēču dzirnavas, Naukšēnu pagasts, Rūjienas novads.', 'Gājeju taka', 'Pļava', 'Grūti',
        2.7, 'trails/92.jpg'),
       (93, 'Jēču dabas taka', 'Jēču dzirnavas, Naukšēnu pagasts, Rūjienas novads.', 'Gājeju taka', 'Pļava', 'Grūti',
        7.6, 'trails/93.jpg'),
       (94, 'Kaltenes putnu vērošanas taka', 'Kaltene, Rojas pagasts, Talsu novads, LV-3264', 'Gājeju taka',
        'Piekraste', 'Normāli', 1, 'trails/94.jpg'),
       (95, 'Oleru purva taka', 'Jeru pagasts, Valmieras novads, LV-4234', 'Gājeju taka', 'Purvs, tīrums', 'Normāli',
        1.1, 'trails/95.jpg'),
       (96, 'Orhideju taka', 'Dabas parks Engures ezers, Bērzciems', 'Gājeju taka', 'Pļava, ezers', 'Normāli', 5,
        'trails/96.jpg'),
       (97, 'Apkārt Vaidavas ezeram', 'Vaidavas ezers, Vaidavas pagasts, Valmieras novads', 'Gājeju taka, velotaka',
        'Ezers', 'Normāli', 12, 'trails/97.jpg'),
       (98, 'Līgatnes dabas takas', 'Līgatnes dabas takas Līgatnes novads, Līgatne, LV-4108', 'Gājeju taka', 'Mežs',
        'Viegli', 5, 'trails/98.jpg'),
       (99, 'Papes ekoloģisko procesu taka', 'Papes dabas parks, Pape.', 'Gājeju taka, velotaka', 'Mežs, purvs',
        'Normāli', 9.6, 'trails/99.jpg'),
       (100, 'Raipala ezera taka', 'Korneti, Veclaicenes pagasts, Alūksnes novads, LV-4335', 'Gājeju taka', 'Ezers',
        'Viegli', 2.5, 'trails/100.jpg'),
       (101, 'Zīles taka', '57.70281, 26.04685', 'Gājeju taka', 'Mežs', 'Viegli', 2.5, 'trails/101.jpg'),
       (102, 'Kokneses dabas taka', 'Koknese, Kokneses pagasts, LV-5113', 'Gājeju taka', 'Mežs, upe', 'Viegli', 5.65,
        'trails/102.jpg'),
       (103, 'Skaņākalna taka', 'Parka iela 36, Mazsalaca, Mazsalacas pilsēta, Valmieras novads, LV-4215',
        'Gājeju taka', 'Mežs, upe', 'Normāli', 3, 'trails/103.jpg'),
       (104, 'Planču purva taka', 'Staiceles pagasts, Limbažu novads, LV-4043', 'Gājeju taka', 'Purvs', 'Viegli', 0.5,
        'trails/104.jpg'),
       (105, 'Vasenieku purva taka', 'Vasenieku purvs, Puzes pagasts, Ventspils novads', 'Gājeju taka', 'Purvs',
        'Viegli', 5, 'trails/105.jpg'),
       (106, 'Sildu dabas taka', 'Mētrienas pag., Madonas nov. 56.66033744481551, 26.35144100051879', 'Gājeju taka',
        'Purvs', 'Normāli', 3.5, 'trails/106.jpg'),
       (107, 'Kupskalnu dabas taka', 'Jaunā iela 3, Lapmežciems, Lapmežciema pagasts, Tukuma novads, LV-3118',
        'Gājeju taka', 'Krasts', 'Viegli', 0.5, 'trails/107.jpg'),
       (108, 'Pēterezera dabas taka', 'Kolkas pagasts, Talsu novads, LV-3275', 'Gājeju taka', 'Mežs, ezers', 'Normāli',
        3.4, 'trails/108.jpg'),
       (109, 'Ciriša Upursalas taka', '56.131985, 26.9898', 'Gājeju taka', 'Mežs, ezers', 'Normāli', 1.8,
        'trails/109.jpg'),
       (110, 'Ķirbižu meža izziņas taka', 'Vālodzes, Ķirbiži, Viļķenes pagasts, Limbažu nova', 'Gājeju taka',
        'Mežs, upe', 'Normāli', 2, 'trails/110.jpg'),
       (111, 'Kokšu ezeru dabas taka', 'Zīle, Valkas pagasts, Valkas novads, LV-4701', 'Gājeju taka', 'Ezers',
        'Normāli', 2.7, 'trails/111.jpg'),
       (112, 'Kokšu ezeru dabas taka', 'Zīle, Valkas pagasts, Valkas novads, LV-4702', 'Gājeju taka', 'Ezers',
        'Normāli', 4.5, 'trails/112.jpg'),
       (113, 'Ungurmuižas dižkoku taka', 'Pārgaujas novads, Raiskuma pagasts, Unguri', 'Gājeju taka', 'Tīrums',
        'Viegli', 1.3, 'trails/113.jpg'),
       (114, 'Pūrciema Baltās kāpas taka', 'Ģipka, Rojas pagasts, Talsu novads, LV-3264', 'Gājeju taka', 'Kāpa',
        'Normāli', 0.9, 'trails/114.jpg');
INSERT INTO users (id, username, password, email, role)
VALUES (1, 'janisparaugs', 'qwerty', 'janis.paraugs@example.com', 'ROLE_USER'),
       (2, 'AnnaLiepa', 'parole123', 'anna.liepa@example.com', 'ROLE_USER'),
       (3, 'Māris', 'asdfgh', 'maris@example.com', 'ROLE_USER'),
       (4, 'Ilze', 'zxcvbn', 'ilze@example.com', 'ROLE_USER'),
       (5, 'Andris', '1234p', 'andris@example.com', 'ROLE_USER'),
       (6, 'admin', 'admin', 'admin@example.com', 'ROLE_ADMIN');

INSERT INTO friends (user1_id, friend_id)
VALUES (1, 2),
       (1, 5);

INSERT INTO favorites (user_id, trail_id)
VALUES (1, 101),
       (1, 102),
       (2, 103);

INSERT INTO sessions (user1_id, user2_id, invitecode)
VALUES (1, 2, 54321),
       (3, 5, 67891);