INSERT INTO trails (trail_id, name, location, type, biome, difficulty, length) VALUES
(1, 'Aklā purva taka', 'Daudzeses pagasts, Aizkraukles novads, LV-5111', 'Gājēju taka', 'Purvs', 'Viegli', 1.9),
(2, 'Akmeņu taka', 'Jaunstašuļi, Mākoņkalna pagasts, Rēzeknes novads, LV-4626', 'Gājēju taka', 'Mežs', 'Normāli', 2.3),
(3, 'Amatas ģeotaka. Melturi - Kārļu zivjaudzētava', 'Drabešu pagasts, Cēsu novads. Melturi: 57.2218595, 25.2359774. Kārļu zivjaudzētava: 57.2374353, 25.2011978', 'Gājēju taka', 'Mežs, upe', 'Grūti', 3.6),
(4, 'Amatas ģeotaka. Kārļu zivjaudzētava - Zvārtes iezis', 'Drabešu pagasts, Cēsu novads. Kārļu zivjaudzētava: 57.2374353, 25.2011978 Zvārtes iezis: 57.2459047, 25.1432441', 'Gājēju taka', 'Mežs, upe', 'Normāli', 9.2),
(5, 'Amatas ģeotaka. Zvārtes iezis - Veclauču tilts', 'Drabešu pagasts, Cēsu novads. Zvārtes iezis: 57.2459047, 25.1432441; Veclauču tilts: 57.2617720, 25.1379117', 'Gājēju taka', 'Upe', 'Viegli', 2.4),
(6, 'Andrupenes purva taka', 'Skolas iela 5, Andrupene, Andrupenes pagasts, Krāslavas novads', 'Gājēju taka', 'Purvs', 'Viegli', 0.8),
(7, 'Augstrozes pilskalna taka', 'Umurgas pagasts, Limbažu novads, LV-4004', 'Gājēju taka', 'Tīrums', 'Grūti', 0.5),
(8, 'Barona taka', 'Vilces pagasts, Jelgavas novads. 56.42091763152077, 23.54215030025643', 'Gājēju taka', 'Mežs', 'Viegli', 2.5),
(9, 'Bernātu dabas parka taka', 'Bernāti, Nīcas pagasts, Dienvidkurzemes novads, LV-3473', 'Gājēju taka', 'Mežs', 'Grūti', 1.5),
(10, 'Cenas tīreļa laipu taka', 'Babītes pagasts, Mārupes novads, LV-2107', 'Gājēju taka', 'Purvs', 'Viegli', 6),
(11, 'Cecīļu dabas taka', 'Cecīļu iela 12, Ieriķi, Drabešu pagasts, Cēsu novads, LV-4139', 'Gājēju taka', 'Mežs', 'Grūti', 1.5),
(12, 'Cīrulīšu takas Nr. 1', 'Apšukalna iela 5, Cēsis, Cēsu pilsēta, Cēsu novads, LV-4101', 'Gājēju taka', 'Mežs', 'Normāli', 2.5),
(13, 'Cīrulīšu takas Nr. 2', 'Apšukalna iela 5, Cēsis, Cēsu pilsēta, Cēsu novads, LV-4102', 'Gājēju taka', 'Mežs', 'Normāli', 3.5),
(14, 'Cīrulīšu takas Nr. 3', 'Apšukalna iela 5, Cēsis, Cēsu pilsēta, Cēsu novads, LV-4103', 'Gājēju taka', 'Mežs', 'Normāli', 5.7),
(15, 'Čužu purva taka', 'Kandava, Kandava pilsēta, Tukuma novads, LV-3120', 'Gājēju taka', 'Purvs', 'Viegli', 4),
(16, 'Daugavgrīvas dabas taka', 'Dabas parks Piejūra, Rīga. 57.03688, 24.01852', 'Gājēju taka, velotaka', 'Purvs, tīrums', 'Viegli', 1),
(17, 'Dabas procesu taka', 'Pape, Rucavas pagasts, Dienvidkurzemes novads, LV-3477', 'Gājēju taka', 'Pļava, mežs, purvs', 'Normāli', 9.1),
(18, 'Dauģēnu taka', '57.87415, 24.99788', 'Gājēju taka, velotaka', 'Mežs', 'Grūti', 9.1),
(19, 'Dinaburgas taka', 'Naujenes pagasts, Augšdaugavas novads. 55.911272 , 26.726717000000008', 'Gājēju taka', 'Tīrums', 'Normāli', 0.6),
(20, 'Drusku pilskalna taka', '57.59448, 26.93333', 'Gājēju taka', 'Mežs', 'Grūti', 3.5),
(21, 'Dunikas purva taka', 'Dunikas pagasts, Dienvidkurzemes novads', 'Gājēju taka', 'Purvs', 'Viegli', 5),
(22, 'Dullā Daukas birzs', 'Meņģeles pag., Ogres nov. 56.839275511712025, 25.35594100668977', 'Gājēju taka', 'Mežs', 'Viegli', 0.8),
(23, 'Dziļezera-Riebezera taka', 'Jumpravmuiža, Limbažu pagasts, Limbažu novads, LV-4001', 'Gājēju taka', 'Ezers', 'Grūti', 3.7),
(24, 'Ellītes sēravota taka', 'Daudzeva, Daudzeses pagasts, Aizkraukles novads, LV-5111', 'Gājēju taka', 'Mežs', 'Viegli', 0.3),
(25, 'Embūtes taka Nr. 1', 'Embūtes pagasts, Dienvidkurzemes novads, LV-3436', 'Gājēju taka', 'Mežs', 'Grūti', 3),
(26, 'Embūtes taka Nr. 2', 'Embūtes pagasts, Dienvidkurzemes novads, LV-3437', 'Gājēju taka', 'Mežs', 'Grūti', 5),
(27, 'Ēvažu taka', 'Kurzeme, Ēvaži, Kolkas pagasts, Talsu novads', 'Gājēju taka', 'Piekraste', 'Normāli', 0.3),
(28, 'Gaujas taka Nr. 1', '57.623440, 25.690126', 'Gājēju taka', 'Upe', 'Normāli', 5),
(29, 'Gaujas taka Nr. 2', '57.623440, 25.690127', 'Gājēju taka', 'Upe', 'Normāli', 7),
(30, 'Gaujienas taka', '57.52202, 26.38903', 'Gājēju taka', 'Tīrums', 'Viegli', 6),
(31, 'Imulas taka', 'Matkules pagasts, Tukuma novads, LV-3132', 'Gājēju taka', 'Mežs, upe', 'Normāli', 5),
(32, 'Jaundomes muižas taka', 'Jaundomes muiža, Novomisļi, Ezernieku pagasts, Dagdas novads. 56.1480680999648, 27.61438996711629', 'Gājēju taka', 'Mežs', 'Viegli', 2),
(33, 'Bērza taka', 'Sarkaņkalns", Plikpūrmaļi, Vērēmu pagasts, Rēzeknes novads', 'Gājēju taka', 'Mežs', 'Normāli', 2),
(34, 'Baskāju taka', 'Kurzeme, Valgums, Atpūtas komplekss, Smārdes pagasts, Tukuma novads, LV-3129', 'Gājēju taka', 'Tīrums', 'Viegli', 2.9),
(35, 'Bišu taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Tīrums', 'Viegli', 0.2),
(36, 'Putnu taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Tīrums', 'Viegli', 0.2),
(37, 'Meža taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Mežs un upe', 'Normāli', 2.3),
(38, 'Augu taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Tīrums', 'Viegli', 0.7),
(39, 'Sporta taka', 'Laumas, Īves pagasts, Talsu novads, LV-3261', 'Gājēju taka', 'Tīrums', 'Grūti', 0.5),
(40, 'Sietiņieža dabas taka', 'Sietiņiezis, Vaidavas pagasts, Valmieras novads, LV-4228', 'Gājēju taka', 'Mežs', 'Viegli', 1.4),
(41, 'Sedas purva kājnieku maršruts Jērcēnu aplis', 'Latvija, Vidzeme, Strenču novads, 57.7055987, 25.7001324', 'Gājēju taka', 'Purvs', 'Normāli', 5.5),
(42, 'Sedas purva kājnieku maršruts Sedas aplis', 'Latvija, Vidzeme, Strenču novads, 57.6699587, 25.7514815', 'Gājēju taka', 'Purvs', 'Grūti', 7.5),
(43, 'Melnalkšņu dumbrāju taka', 'Meža māja, Jūrmala, LV-2012', 'Gājēju taka', 'Mežs', 'Viegli', 0.6),
(44, 'Slokas ezera dabas taka', 'Dūņu ceļš, Jūrmala, LV-2012', 'Gājēju taka', 'Ezers', 'Viegli', 3.1),
(45, 'Vikmestes taka', 'Krimuldas pagasts, Siguldas novads, LV-2150', 'Gājēju taka', 'Mežs', 'Viegli', 3),
(46, 'Vizlas dabas taka', 'Vidaga, Virešu pagasts, Smiltenes novads, LV-4355, 57.43061, 26.34762', 'Gājēju taka', 'Upe', 'Normāli', 1.2),
(47, 'Raganu purva taka', 'Lapmežciema pagasts, Tukuma novads, LV-3118', 'Gājēju taka', 'Purvs', 'Viegli', 0.8),
(48, 'Kubeseles dabas un vēstures taka', 'Krimuldas evaņģēliski luteriskā baznīca, Krimuldas pagasts, Siguldas novads', 'Gājēju taka', 'Mežs un upe', 'Viegli', 3.9),
(49, 'Brīvdabas taka gar Rojas upi mazais loks', 'Kāpu iela, Roja, Rojas pagasts, Talsu novads, LV-3264', 'Gājēju taka, velotaka', 'Mežs un upe', 'Viegli', 2),
(50, 'Brīvdabas taka gar Rojas upi vidējais loks', 'Kāpu iela, Roja, Rojas pagasts, Talsu novads, LV-3264', 'Gājēju taka, velotaka', 'Mežs un upe', 'Normāli', 7),
(51, 'Brīvdabas taka gar Rojas upi lielais loks', 'Kāpu iela, Roja, Rojas pagasts, Talsu novads, LV-3264', 'Gājēju taka, velotaka', 'Mežs un upe', 'Grūti', 15),
(52, 'Asares veselības taka', 'Aknīstes novads, Asares pagasts, Asare, Vecmuiža, LV-5210', 'Gājēju taka', 'Tīrums', 'Viegli', 0.5),
(53, 'Plieņciema laipu taka', 'Plieņciems, Engures pagasts, Tukuma novads, LV-3113', 'Gājēju taka', 'Piejūras kāpa', 'Viegli', 3.5),
(54, 'Gārsenes dabas takas', 'Gārsene, Gārsenes pagasts, Jēkabpils novads, LV-5218', 'Gājeju taka', 'Mežs', 'Normāli', 7),
(55, 'Ieriķu dzirnavu dabas taka', 'Ieriķi, Drabešu pagasts, Cēsu novads, LV-4139', 'Gājēju taka', 'Upe', 'Normāli', 1),
(56, 'Pokaiņu takas', 'Pokaiņi, "Senpokaiņi", Dobeles novads', 'Gājēju taka', 'Mežs', 'Normāli', 15),
(57, 'Ziemassvētku kauju piemiņas parka taka', '56.82956, 23.70139', 'Gājēju taka', 'Mežs', 'Grūti', 7.2),
(58, 'Latvijas vēstures taka Nītaurē', 'Nītaure, Nītaures pagasts, Cēsu novads, LV-4112', 'Gājēju taka', 'Mežs', 'Viegli', 3),
(59, 'Kalvu taka', 'Kaltene, Rojas pag., Talsu nov., 57.458110245127514,22.855964348726122', 'Gājēju taka', 'Mežs', 'Grūti', 1.5),
(60, 'Kartavkalna taka', '56.716568, 23.017921', 'Gājēju taka', 'Mežs', 'Viegli', 1.1),
(61, 'Randātu dabas taka', 'Vireši, Virešu pagasts, Smiltenes novads, LV-4355', 'Gājēju taka', 'Klintis', 'Normāli', 1.2),
(62, 'Vīsraga dabas taka', '57.698035, 25.276864', 'Gājeju taka, velotaka', 'Pļava', 'Viegli', 2),
(63, 'Limbažu Lielezera taka', 'Lielezera iela 14, Limbaži', 'Gājeju taka', 'Ezers', 'Viegli', 2.3),
(64, 'Vekšu taka', 'Vekši, Valkas pag., LV-4701, 57.691150, 26.053069', 'Gājeju taka', 'Tīrums', 'Viegli', 0.5),
(65, 'Jāņkalnu folkloras taka', 'Jāņkalni", Lībagu pagasts, Talsu novads', 'Gājeju taka', 'Tīrums', 'Viegli', 0.2),
(66, 'Dabas taka "Rīvas loki', 'Jūrkalnes pagasts, Ventspils novads, LV-3626', 'Gājeju taka', 'Upe', 'Grūti', 8),
(67, 'Markovas izziņas taka un Markovas pilskalns', '55.916794 , 26.892548, Sprukti, Naujenes pagasts', 'Gājeju taka', 'Mežs', 'Viegli', 1.6),
(68, 'Kolkasraga priežu taka', 'Kolkas pagasts, Dundagas novads, 57.75690585102602, 22.591081627204712', 'Gājeju taka', 'Mežs, tīrums', 'Viegli', 1.2),
(69, 'Žibgravas veselības taka', '56.984217, 21.578783', 'Gājeju taka', 'Mežs', 'Normāli', 1.2),
(70, 'Ukru gāršas takas', 'Bukaišu pagasts, Dobeles novads, LV-3714', 'Gājeju taka', 'Mežs', 'Normāli', 2),
(71, 'Viesatas upesloku taka', '56.81726, 22.94729', 'Gājeju taka', 'Mežs, upe', 'Normāli', 4),
(72, 'Viesatas upesloku taka', '56.81726, 22.94730', 'Gājeju taka', 'Mežs, upe', 'Normāli', 6),
(73, 'Akmeņupītes taka', 'Jaunstašuļi, Mākoņkalna pagasts, Rēzeknes novads', 'Gājeju taka', 'Mežs', 'Viegli', 1.2),
(74, 'Zaķumuižas dabas taka', 'Parka iela, Zaķumuiža, Ropažu pagasts, Ropažu novads, LV-2133', 'Gājeju taka', 'Tīrums', 'Viegli', 1.8),
(75, 'Sprīdīša taka', 'Pilskalne, Pilskalnes pagasts, Augšdaugavas novads', 'Gājeju taka', 'Tīrums', 'Viegli', 1.6),
(76, 'Dendroloģiskais un ģeogrāfiskais maršruts', 'Pilskalne, Pilskalnes pagasts, Augšdaugavas novads', 'Gājeju taka', 'Mežs', 'Viegli', 3.8),
(77, 'Taka “Vēstures liecinieki”', 'Pilskalne, Pilskalnes pagasts, Augšdaugavas novads', 'Gājeju taka', 'Mežs', 'Viegli', 5),
(78, 'Pilskalnes Siguldiņas purva taka', 'Pilskalne, Pilskalnes pagasts, Augšdaugavas novads', 'Gājeju taka', 'Purvs', 'Normāli', 6),
(79, 'Kaņiera niedrāja taka', 'Kaņiera ezera niedru taka, Lapmežciema pagasts, Tukuma novads', 'Gājeju taka', 'Ezers', 'Grūti', 0.6),
(80, 'Teirumnīku purva taka', 'Nagļu pagasts, Rēzeknes novads', 'Gājeju taka, velotaka', 'Ezers, purvs', 'Viegli', 0.8),
(81, 'Drubazu dabas taka', '57.030415, 22.59661', 'Gājeju taka', 'Pļava', 'Viegli', 1.2),
(82, 'Drubazu dabas taka', '57.030415, 22.59662', 'Gājeju taka', 'Pļava', 'Normāli', 2),
(83, 'Adamovas taka', 'Augusta iela 3A, Krāslava, Krāslavas pilsēta, Krāslavas novads, LV-5601', 'Gājeju taka', 'Mežs, upe', 'Normāli', 1.8),
(84, 'Niedrāju - Pilkas purva taka', 'Niedrāju–Pilkas purvs, Pāles pagasts, Limbažu novads', 'Gājeju taka', 'Purvs', 'Viegli', 1),
(85, 'Minhauzena taka', 'Duntes muiža, Liepupes pagasts', 'Gājeju taka', 'Mežs, Krasts', 'Viegli', 1.1),
(86, 'Minhauzena taka', 'Duntes muiža, Liepupes pagasts', 'Gājeju taka', 'Mežs, Krasts', 'Viegli', 3),
(87, 'Minhauzena taka', 'Duntes muiža, Liepupes pagasts', 'Gājeju taka', 'Mežs, Krasts', 'Viegli', 4.4),
(88, 'Ragakāpas dabas taka', 'Tīklu iela 1a, Buļļuciems,  56.9961349, 23.9155135', 'Gājeju taka', 'Mežs', 'Normāli', 2),
(89, 'Murjāņi - Sigulda taka', 'Puķu iela 4, Sigulda', 'Gājeju taka, velotaka', 'Mežs, upe, tīrums', 'Grūti', 30.2),
(90, 'Šlīteres dabas taka', 'Slīteres dabas taka, Dundagas pagasts, Talsu novads, LV-3270', 'Gājeju taka', 'Mežs, purvs', 'Normāli', 1.2),
(91, 'Saulrieta taka', 'Rīgas iela 11A, Saulkrasti, Saulkrastu pilsēta, Saulkrastu novads, LV-2160', 'Gājeju taka', 'Mežs, piekraste', 'Viegli', 3.6),
(92, 'Jēču dabas taka', 'Jēču dzirnavas, Naukšēnu pagasts, Rūjienas novads.', 'Gājeju taka', 'Pļava', 'Grūti', 2.7),
(93, 'Jēču dabas taka', 'Jēču dzirnavas, Naukšēnu pagasts, Rūjienas novads.', 'Gājeju taka', 'Pļava', 'Grūti', 7.6),
(94, 'Kaltenes putnu vērošanas taka', 'Kaltene, Rojas pagasts, Talsu novads, LV-3264', 'Gājeju taka', 'Piekraste', 'Normāli', 1),
(95, 'Oleru purva taka', 'Jeru pagasts, Valmieras novads, LV-4234', 'Gājeju taka', 'Purvs, tīrums', 'Normāli', 1.1),
(96, 'Orhideju taka', 'Dabas parks Engures ezers, Bērzciems', 'Gājeju taka', 'Pļava, ezers', 'Normāli', 5),
(97, 'Apkārt Vaidavas ezeram', 'Vaidavas ezers, Vaidavas pagasts, Valmieras novads', 'Gājeju taka, velotaka', 'Ezers', 'Normāli', 12),
(98, 'Līgatnes dabas takas', 'Līgatnes dabas takas Līgatnes novads, Līgatne, LV-4108', 'Gājeju taka', 'Mežs', 'Viegli', 5),
(99, 'Papes ekoloģisko procesu taka', 'Papes dabas parks, Pape.', 'Gājeju taka, velotaka', 'Mežs, purvs', 'Normāli', 9.6),
(100, 'Raipala ezera taka', 'Korneti, Veclaicenes pagasts, Alūksnes novads, LV-4335', 'Gājeju taka', 'Ezers', 'Viegli', 2.5),
(101, 'Zīles taka', '57.70281, 26.04685', 'Gājeju taka', 'Mežs', 'Viegli', 2.5),
(102, 'Kokneses dabas taka', 'Koknese, Kokneses pagasts, LV-5113', 'Gājeju taka', 'Mežs, upe', 'Viegli', 5.65),
(103, 'Skaņākalna taka', 'Parka iela 36, Mazsalaca, Mazsalacas pilsēta, Valmieras novads, LV-4215', 'Gājeju taka', 'Mežs, upe', 'Normāli', 3),
(104, 'Planču purva taka', 'Staiceles pagasts, Limbažu novads, LV-4043', 'Gājeju taka', 'Purvs', 'Viegli', 0.5),
(105, 'Vasenieku purva taka', 'Vasenieku purvs, Puzes pagasts, Ventspils novads', 'Gājeju taka', 'Purvs', 'Viegli', 5),
(106, 'Sildu dabas taka', 'Mētrienas pag., Madonas nov. 56.66033744481551, 26.35144100051879', 'Gājeju taka', 'Purvs', 'Normāli', 3.5),
(107, 'Kupskalnu dabas taka', 'Jaunā iela 3, Lapmežciems, Lapmežciema pagasts, Tukuma novads, LV-3118', 'Gājeju taka', 'Krasts', 'Viegli', 0.5),
(108, 'Pēterezera dabas taka', 'Kolkas pagasts, Talsu novads, LV-3275', 'Gājeju taka', 'Mežs, ezers', 'Normāli', 3.4),
(109, 'Ciriša Upursalas taka', '56.131985, 26.9898', 'Gājeju taka', 'Mežs, ezers', 'Normāli', 1.8),
(110, 'Ķirbižu meža izziņas taka', 'Vālodzes, Ķirbiži, Viļķenes pagasts, Limbažu nova', 'Gājeju taka', 'Mežs, upe', 'Normāli', 2),
(111, 'Kokšu ezeru dabas taka', 'Zīle, Valkas pagasts, Valkas novads, LV-4701', 'Gājeju taka', 'Ezers', 'Normāli', 2.7),
(112, 'Kokšu ezeru dabas taka', 'Zīle, Valkas pagasts, Valkas novads, LV-4702', 'Gājeju taka', 'Ezers', 'Normāli', 4.5),
(113, 'Ungurmuižas dižkoku taka', 'Pārgaujas novads, Raiskuma pagasts, Unguri', 'Gājeju taka', 'Tīrums', 'Viegli', 1.3),
(114, 'Pūrciema Baltās kāpas taka', 'Ģipka, Rojas pagasts, Talsu novads, LV-3264', 'Gājeju taka', 'Kāpa', 'Normāli', 0.9);

INSERT INTO users (user_id, username, password, email) VALUES
(1, 'janisparaugs', 'qwerty', 'janis.paraugs@example.com'),
(2, 'AnnaLiepa', 'parole123', 'anna.liepa@example.com'),
(3, 'Māris', 'asdfgh', 'maris@example.com'),
(4, 'Ilze', 'zxcvbn', 'ilze@example.com'),
(5, 'Andris', '1234p', 'andris@example.com');

INSERT INTO friends (user1_id, friend_id) VALUES
(1, 2),
(1, 5);

INSERT INTO favorites (user_id, trail_id) VALUES
(1, 101),
(1, 102),
(2, 103);